# ----------------------------------------------------------
# Configuration file for log4r
# ----------------------------------------------------------

log4r_config:
  
 loggers:
  - name: "Log4r"
    type: "Logger"
    level: "INFO"
    trace: "true"
    outputters:
     - "StdOut"
     - "F1"
  
 outputters:
  - name: "StdOut"
    type: "StdoutOutputter"
    level: "DEBUG"
    formatter:
     name: "P1"
     type: "PatternFormatter"
#     pattern: "%d [%l] %c(%t) - %m"
     pattern: "%d [%l] %m"
     date_pattern: "%H:%M:%S"
  - name: "F1"
    type: "FileOutputter"
    filename: "/Users/igakuratakayuki/RubyWorkspace/mrs_server_s/log/mrsss.log"
    trunc: "false"
    formatter:
     name: "P2"
     type: "PatternFormatter"
     pattern: "%d [%l] %C(%t) - %M"
#     pattern: "%d [%l] %M"
     date_pattern: "%Y/%m/%d %H:%M:%S"
