channels: 
 JAL: 
  port: 30000
  archive_path: "/Users/igakuratakayuki/RubyWorkspace/mrs_server_s/tmp/"
  channel_id: "JAL"

 JMA: 
  port: 30001
  archive_path: "/Users/igakuratakayuki/RubyWorkspace/mrs_server_s/tmp/"
  channel_id: "JMA"

# BCHのチェックサム値によるチェック要否
# true チェック要
# false チェック不要
need_checksum: false

# アプリケーションの動作モード
# 0 通常
# 1 訓練
# 2 試験
mode: 1

# Resqueの使用有無
# true 使用
# false 使用しない
use_queue: false
