
basic: 

issues: 
 protocol: "http"
 site: "203.138.187.88"
 prefix: "redmine/issues.json?format=json"
 api_key: "88258d4686dd6aafd8de0a647805a56873d462ac"
 open_timeout: 10
 timeout: 300
 basic_user: "admin"
 basic_password: "1qazxsw2"

uploads: 
 protocol: "http"
 site: "203.138.187.88"
 prefix: "redmine/uploads.json?format=json"
 api_key: "88258d4686dd6aafd8de0a647805a56873d462ac"
 open_timeout: 10
 timeout: 300
 basic_user: "admin"
 basic_password: "1qazxsw2"

pdf_config: 
 subject: "PDFファイル"
 project_id: "I04202000000000000001"
 tracker_id: "4"
 filename: "jma.pdf"
 description: ""
 content_type: "application/pdf"

txt_config: 
 subject: "内閣官房長"
 project_id: "I04202000000000000001"
 tracker_id: "4"
 description: ""
 content_type: "text/plain"

png_config: 
 subject: "PNGファイル"
 project_id: "I04202000000000000001"
 tracker_id: "4"
 filename: "jma.png"
 description: ""
 content_type: "application/png"

bin_config: 
 subject: "BINファイル"
 project_id: "I04202000000000000001"
 tracker_id: "4"
 filename: "jma.bin"
 description: ""
 content_type: "application/bin"
